name: 'Terraform Destroy on Azure'

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Confirm if you want to destroy the Terraform backend (type DESTROY to confirm)'
        required: true
        default: 'DESTROY'

env:
  AZURE_REGION: koreacentral  # 원하는 Azure 리전 (소문자, 예: koreacentral, eastus 등)

jobs:
  backend_destroy:
    name: 'Terraform Destroy Backend'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Azure CLI 로그인 (Service Principal 사용)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Terraform이 Service Principal 인증을 사용하도록 ARM 환경 변수 설정
      - name: Set ARM environment variables
        run: |
          echo "ARM_CLIENT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.8.0'

      - name: Confirm Destruction
        if: ${{ github.event.inputs.confirm_destroy == 'DESTROY' }}
        run: echo "Destruction confirmed. Proceeding with Terraform destroy operation."

      - name: Abort Destruction
        if: ${{ github.event.inputs.confirm_destroy != 'DESTROY' }}
        run: |
          echo "Destruction not confirmed. Exiting workflow without performing destruction."
          exit 1

      - name: Terraform Init for Destroy
        run: |
          cd terraform_source
          terraform init \
            -backend-config="resource_group_name=rg-terraform-backend" \
            -backend-config="storage_account_name=manoittesttfstate" \
            -backend-config="container_name=tfstate-manoit-blob" \
            -backend-config="key=dev/terraform/terraform.tfstate"

      - name: Terraform Destroy
        run: |
          cd terraform_source
          terraform destroy -auto-approve
