apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
  annotations:
    # Azure LB가 /healthz 경로와 10254 포트로 Health Probe를 보내도록 설정
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-port: "10254"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller

  ports:
  - name: http
    port: 80          # 외부에서 접근하는 포트
    targetPort: 80    # 컨트롤러 Pod에서 사용하는 포트 (ingress 기본 http)
