apiVersion: v1
kind: Service
metadata:
  name: my-backend
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: my-backend
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
